# Generated by Django 4.2.2 on 2024-03-14 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True, verbose_name='discipline_title')),
            ],
            options={
                'db_table': 'discipline',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True, verbose_name='faculty_title')),
            ],
            options={
                'db_table': 'faculty',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Gruppa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cipher', models.CharField(max_length=32, unique=True, verbose_name='gruppa_cipher')),
                ('language', models.CharField(max_length=32, verbose_name='language')),
            ],
            options={
                'db_table': 'gruppa',
                'ordering': ['cipher'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dates', models.DateTimeField(verbose_name='dates')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_discipline', to='journal.discipline')),
                ('gruppa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gruppa', to='journal.gruppa')),
            ],
            options={
                'db_table': 'schedule',
                'ordering': ['discipline'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128, verbose_name='full_name')),
                ('sex', models.CharField(choices=[('М', 'М'), ('Ж', 'Ж')], default='М', max_length=1, verbose_name='sex')),
                ('iin', models.CharField(max_length=12, unique=True, verbose_name='iin')),
                ('birthday', models.DateTimeField(verbose_name='birthday')),
                ('phone', models.CharField(max_length=64, verbose_name='phone')),
                ('address', models.CharField(max_length=96, verbose_name='address')),
                ('gruppa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_gruppa', to='journal.gruppa')),
            ],
            options={
                'db_table': 'student',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cipher', models.CharField(max_length=32, unique=True, verbose_name='speciality_cipher')),
                ('title', models.CharField(max_length=256, verbose_name='speciality_title')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speciality_faculty', to='journal.faculty')),
            ],
            options={
                'db_table': 'speciality',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dater', models.DateTimeField(verbose_name='dater')),
                ('course', models.IntegerField(verbose_name='course')),
                ('semester', models.IntegerField(verbose_name='semester')),
                ('value', models.IntegerField(verbose_name='value')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_discipline', to='journal.discipline')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_student', to='journal.student')),
            ],
            options={
                'db_table': 'rating',
                'ordering': ['dater'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daten', models.DateTimeField(verbose_name='daten')),
                ('title', models.CharField(max_length=256, verbose_name='news_title')),
                ('details', models.TextField(verbose_name='news_details')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='news_photo')),
            ],
            options={
                'db_table': 'news',
                'ordering': ['daten'],
                'indexes': [models.Index(fields=['daten'], name='news_daten_a29edb_idx')],
            },
        ),
        migrations.AddField(
            model_name='gruppa',
            name='speciality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gruppa_speciality', to='journal.speciality'),
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited', models.BooleanField(default=False, verbose_name='visited')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_schedule', to='journal.schedule')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_student', to='journal.student')),
            ],
            options={
                'db_table': 'visit',
                'ordering': ['schedule'],
                'indexes': [models.Index(fields=['schedule'], name='visit_schedul_ddc22e_idx'), models.Index(fields=['student'], name='visit_student_b645fd_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['full_name'], name='student_full_na_fb00fe_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['gruppa'], name='student_gruppa__30ec23_idx'),
        ),
        migrations.AddIndex(
            model_name='speciality',
            index=models.Index(fields=['faculty', 'title'], name='speciality_faculty_21d816_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['discipline'], name='schedule_discipl_fccbf7_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['gruppa'], name='schedule_gruppa__0cd0c6_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['dater'], name='rating_dater_08e806_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['discipline'], name='rating_discipl_a5cd7c_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['student'], name='rating_student_1fbb36_idx'),
        ),
        migrations.AddIndex(
            model_name='gruppa',
            index=models.Index(fields=['cipher', 'speciality'], name='gruppa_cipher_ea49a9_idx'),
        ),
    ]
